# Custom ngin configuration file for the Nginx web server
server {
    listen 80;
    server_name localhost;

    # Define the root directory for the server
    root /usr/share/nginx/html;

    # Define the index file
    index index.html;

    # Define the location for static files
    location / {
        try_files $uri $uri/ =404;
    }


    # Enable gzip compression
    gzip on;
    gzip_types text/plain application/javascript text/css image/svg+xml;
    
    # Set up error logging
    error_log /var/log/nginx/error.log warn;
    
    # Set up access logging
    access_log /var/log/nginx/access.log;

    # Cache static files for better performance
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}